sumeru.packages(
   'config',
   'controller',
   'model',
   'library',
   'assets/css/framework.css',
   'assets/js/jquery-1.10.2.min.js',
   'assets/js/jquery.banner.js',
   'assets/js/highcharts.js',
   'assets/js/unslider.js',
   'assets/js/jquery.event.swipe.js'
)
