//出租房
Model.houseRent = function(exports){
    exports.config = {
        fields : [
            { name: 'address', type: 'string'},
			{ name: 'id', type: 'number'},
			{ name: 'type', type: 'string'},
			{ name: 'lat', type: 'string'},
			{ name: 'lng', type: 'string'},
			{ name: 'distance', type: 'number'},
			{ name: 'picURL', type: 'string'},
			{ name: 'rentStatus', type: 'number'},
            { name: 'rentPrice', type: 'string'},
			{ name: 'residenceName', type: 'string'},
			{ name: 'price', type: 'string'},
			{ name: 'roomType', type: 'string'},
			{ name: 'area', type: 'string'},
			{ name: 'decorating', type: 'string'},
			{ name: 'direction', type: 'string'},
            { name: 'floor', type: 'number'},
            { name: 'isEmergent', type: 'string'},
            { name: 'isRecommend', type: 'string'},
            { name: 'isFollow', type: 'string'},
            { name: 'combinedRent', type: 'string'},
            { name: 'fansCount', type: 'number'},
            { name: 'askedCount', type: 'number'},
            { name: 'isNew', type: 'string'},
            { name: 'dealTimeRent', type: 'datetime'},
            { name: 'onboardTime', type: 'datetime'},
			{ name: 'residencePicURL', type: 'array'},
			{ name: 'floorLevel', type: 'string'},
			{ name: 'plateName', type: 'string'},
            { name: 'auditComments', type: 'string'},
			{ name: 'onboardTimeString', type: 'string'},
			{ name: 'picURLWithSize', type: 'string'},
			{ name: 'residencePicURLWithSize', type: 'array'},
			{ name: 'residencePicURLWithOriginSize', type: 'array'},
			{ name: 'followTIme', type: 'number'},
            { name: 'applyTimeString', type: 'string'},
            { name: 'updateTimeString', type: 'string'},
            { name: 'rentRec', type: 'string'},
        ]
    }
}
